using System;
using System.Globalization;
using System.IO;
using System.Text;
using Godot;

[Tool]
public partial class TerrainExporter : EditorScript
{
	private const string TerrainNodeName = "TerrainSource";
	private const string OutputPath = "res://Shared/TerrainHeightData.generated.cs";
	private const int OutputResolution = 65;

	public override void _Run()
	{
		var sceneRoot = EditorInterface.Singleton.GetEditedSceneRoot();
		if (sceneRoot == null)
		{
			GD.PushError("No edited scene root found.");
			return;
		}

		var terrainNode = sceneRoot.FindChild(TerrainNodeName, true, false) as MeshInstance3D;
		if (terrainNode == null)
		{
			GD.PushError($"Could not find a MeshInstance3D named '{TerrainNodeName}' in the edited scene.");
			return;
		}

		if (terrainNode.Mesh == null)
		{
			GD.PushError($"'{TerrainNodeName}' does not have a mesh.");
			return;
		}

		var sampleBounds = DetermineSampleBounds(terrainNode);
		var heights = SampleTerrain(terrainNode, sampleBounds, OutputResolution);
		var output = BuildGeneratedFile(sampleBounds, heights, OutputResolution);

		var absolutePath = ProjectSettings.GlobalizePath(OutputPath);
		Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);
		File.WriteAllText(absolutePath, output, Encoding.UTF8);
		GD.Print($"Terrain data exported to {OutputPath}");
	}

	private static Aabb DetermineSampleBounds(MeshInstance3D terrainNode)
	{
		var aabb = terrainNode.GlobalTransform * terrainNode.Mesh.GetAabb();
		return new Aabb(
			new Vector3(aabb.Position.X, aabb.Position.Y, aabb.Position.Z),
			new Vector3(aabb.Size.X, aabb.Size.Y, aabb.Size.Z)
		);
	}

	private static float[] SampleTerrain(MeshInstance3D terrainNode, Aabb bounds, int resolution)
	{
		var triangles = MeshTriangles.FromMesh(terrainNode);
		var heights = new float[resolution * resolution];
		var stepX = bounds.Size.X / (resolution - 1);
		var stepZ = bounds.Size.Z / (resolution - 1);

		for (var z = 0; z < resolution; z++)
		{
			for (var x = 0; x < resolution; x++)
			{
				var worldX = bounds.Position.X + x * stepX;
				var worldZ = bounds.Position.Z + z * stepZ;
				heights[z * resolution + x] = triangles.SampleHeight(worldX, worldZ);
			}
		}

		return heights;
	}

	private static string BuildGeneratedFile(Aabb bounds, float[] heights, int resolution)
	{
		var maxHeight = float.MinValue;
		foreach (var height in heights)
		{
			if (height > maxHeight)
			{
				maxHeight = height;
			}
		}

		var builder = new StringBuilder();
		builder.AppendLine("// Auto-generated by TerrainExporter.cs");
		builder.AppendLine("public static partial class TerrainHeightData");
		builder.AppendLine("{");
		builder.AppendLine($"    public const float MinX = {Format(bounds.Position.X)}f;");
		builder.AppendLine($"    public const float MaxX = {Format(bounds.End.X)}f;");
		builder.AppendLine($"    public const float MinZ = {Format(bounds.Position.Z)}f;");
		builder.AppendLine($"    public const float MaxZ = {Format(bounds.End.Z)}f;");
		builder.AppendLine($"    public const float WorldRadius = {Format(bounds.Size.X / 2f)}f;");
		builder.AppendLine($"    public const float SummitHeight = {Format(maxHeight)}f;");
		builder.AppendLine($"    public const int Resolution = {resolution};");
		builder.AppendLine("    public static readonly float[] Heights =");
		builder.AppendLine("    [");

		for (var i = 0; i < heights.Length; i++)
		{
			builder.Append("        ");
			builder.Append(Format(heights[i]));
			builder.Append("f");
			if (i < heights.Length - 1)
			{
				builder.Append(",");
			}

			if ((i + 1) % 8 == 0 || i == heights.Length - 1)
			{
				builder.AppendLine();
			}
		}

		builder.AppendLine("    ];");
		builder.AppendLine("}");
		return builder.ToString();
	}

	private static string Format(float value)
		=> value.ToString("0.######", CultureInfo.InvariantCulture);

	private readonly record struct Triangle(Vector3 A, Vector3 B, Vector3 C)
	{
		public bool TrySampleHeight(float x, float z, out float y)
		{
			var a2 = new Vector2(A.X, A.Z);
			var b2 = new Vector2(B.X, B.Z);
			var c2 = new Vector2(C.X, C.Z);
			var point = new Vector2(x, z);

			var denominator = (b2.Y - c2.Y) * (a2.X - c2.X) + (c2.X - b2.X) * (a2.Y - c2.Y);
			if (MathF.Abs(denominator) < 0.00001f)
			{
				y = 0f;
				return false;
			}

			var w1 = ((b2.Y - c2.Y) * (point.X - c2.X) + (c2.X - b2.X) * (point.Y - c2.Y)) / denominator;
			var w2 = ((c2.Y - a2.Y) * (point.X - c2.X) + (a2.X - c2.X) * (point.Y - c2.Y)) / denominator;
			var w3 = 1f - w1 - w2;

			const float epsilon = -0.0001f;
			if (w1 < epsilon || w2 < epsilon || w3 < epsilon)
			{
				y = 0f;
				return false;
			}

			y = A.Y * w1 + B.Y * w2 + C.Y * w3;
			return true;
		}
	}

	private sealed class MeshTriangles
	{
		private readonly Triangle[] _triangles;

		private MeshTriangles(Triangle[] triangles)
		{
			_triangles = triangles;
		}

		public static MeshTriangles FromMesh(MeshInstance3D terrainNode)
		{
			var triangleList = new System.Collections.Generic.List<Triangle>();
			var mesh = terrainNode.Mesh;
			var transform = terrainNode.GlobalTransform;

			for (var surface = 0; surface < mesh.GetSurfaceCount(); surface++)
			{
				var arrays = mesh.SurfaceGetArrays(surface);
				var vertices = (Vector3[])arrays[(int)Mesh.ArrayType.Vertex];
				var indices = (int[])arrays[(int)Mesh.ArrayType.Index];

				if (indices.Length > 0)
				{
					for (var i = 0; i < indices.Length; i += 3)
					{
						triangleList.Add(new Triangle(
							transform * vertices[indices[i]],
							transform * vertices[indices[i + 1]],
							transform * vertices[indices[i + 2]]
						));
					}
				}
				else
				{
					for (var i = 0; i < vertices.Length; i += 3)
					{
						triangleList.Add(new Triangle(
							transform * vertices[i],
							transform * vertices[i + 1],
							transform * vertices[i + 2]
						));
					}
				}
			}

			return new MeshTriangles(triangleList.ToArray());
		}

		public float SampleHeight(float x, float z)
		{
			var found = false;
			var bestHeight = float.MinValue;

			foreach (var triangle in _triangles)
			{
				if (!triangle.TrySampleHeight(x, z, out var sampledHeight))
				{
					continue;
				}

				if (!found || sampledHeight > bestHeight)
				{
					bestHeight = sampledHeight;
					found = true;
				}
			}

			if (!found)
			{
				throw new InvalidOperationException($"No terrain height found at ({x}, {z}).");
			}

			return bestHeight;
		}
	}
}
