using System;
using System.Globalization;
using System.IO;
using System.Text;
using Godot;

[Tool]
public partial class TerrainExporter : EditorScript
{
	private const string TerrainNodeName = "TerrainSource";
	private const string OutputPath = "res://Shared/TerrainHeightData.generated.cs";
	private const int OutputResolution = 65;
	private const string IncludeGroupName = "terrain_export";
	private const string ExcludeGroupName = "terrain_ignore";
	private const string IncludeMetaName = "terrain_export";
	private const string ExcludeMetaName = "terrain_ignore";

	public override void _Run()
	{
		var sceneRoot = EditorInterface.Singleton.GetEditedSceneRoot();
		if (sceneRoot == null)
		{
			GD.PushError("No edited scene root found.");
			return;
		}

		var terrainRoot = sceneRoot.FindChild(TerrainNodeName, true, false) as Node3D;
		if (terrainRoot == null)
		{
			GD.PushError($"Could not find a Node3D named '{TerrainNodeName}' in the edited scene.");
			return;
		}

		var terrainGeometry = TerrainGeometry.FromRoot(terrainRoot);
		if (terrainGeometry.MeshCount == 0)
		{
			GD.PushError($"'{TerrainNodeName}' does not contain any MeshInstance3D nodes with meshes.");
			return;
		}

		var sampleBounds = terrainGeometry.Bounds;
		var sampleData = SampleTerrain(terrainGeometry, sampleBounds, OutputResolution);
		var output = BuildGeneratedFile(sampleBounds, sampleData, OutputResolution);

		var absolutePath = ProjectSettings.GlobalizePath(OutputPath);
		Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);
		File.WriteAllText(absolutePath, output, Encoding.UTF8);
		GD.Print($"Terrain data exported to {OutputPath}");
	}

	private static TerrainSampleData SampleTerrain(TerrainGeometry terrainGeometry, Aabb bounds, int resolution)
	{
		var heights = new float[resolution * resolution];
		var groundMask = new byte[resolution * resolution];
		var stepX = bounds.Size.X / (resolution - 1);
		var stepZ = bounds.Size.Z / (resolution - 1);

		for (var z = 0; z < resolution; z++)
		{
			for (var x = 0; x < resolution; x++)
			{
				var worldX = bounds.Position.X + x * stepX;
				var worldZ = bounds.Position.Z + z * stepZ;
				var index = z * resolution + x;
				groundMask[index] = terrainGeometry.TrySampleHeightExact(worldX, worldZ, out _) ? (byte)1 : (byte)0;
				heights[index] = terrainGeometry.SampleHeightOrNearest(worldX, worldZ, stepX, stepZ);
			}
		}

		return new TerrainSampleData(heights, groundMask);
	}

	private static string BuildGeneratedFile(Aabb bounds, TerrainSampleData sampleData, int resolution)
	{
		var maxHeight = float.MinValue;
		foreach (var height in sampleData.Heights)
		{
			if (height > maxHeight)
			{
				maxHeight = height;
			}
		}

		var builder = new StringBuilder();
		builder.AppendLine("// Auto-generated by TerrainExporter.cs");
		builder.AppendLine("public static partial class TerrainHeightData");
		builder.AppendLine("{");
		builder.AppendLine($"    public const float MinX = {Format(bounds.Position.X)}f;");
		builder.AppendLine($"    public const float MaxX = {Format(bounds.End.X)}f;");
		builder.AppendLine($"    public const float MinZ = {Format(bounds.Position.Z)}f;");
		builder.AppendLine($"    public const float MaxZ = {Format(bounds.End.Z)}f;");
		builder.AppendLine($"    public const float WorldRadius = {Format(bounds.Size.X / 2f)}f;");
		builder.AppendLine($"    public const float SummitHeight = {Format(maxHeight)}f;");
		builder.AppendLine($"    public const int Resolution = {resolution};");
		builder.AppendLine("    public static readonly float[] Heights =");
		builder.AppendLine("    [");

		for (var i = 0; i < sampleData.Heights.Length; i++)
		{
			builder.Append("        ");
			builder.Append(Format(sampleData.Heights[i]));
			builder.Append("f");
			if (i < sampleData.Heights.Length - 1)
			{
				builder.Append(",");
			}

			if ((i + 1) % 8 == 0 || i == sampleData.Heights.Length - 1)
			{
				builder.AppendLine();
			}
		}

		builder.AppendLine("    ];");
		builder.AppendLine("    public static readonly byte[] GroundMask =");
		builder.AppendLine("    [");

		for (var i = 0; i < sampleData.GroundMask.Length; i++)
		{
			builder.Append("        ");
			builder.Append(sampleData.GroundMask[i].ToString(CultureInfo.InvariantCulture));
			if (i < sampleData.GroundMask.Length - 1)
			{
				builder.Append(",");
			}

			if ((i + 1) % 16 == 0 || i == sampleData.GroundMask.Length - 1)
			{
				builder.AppendLine();
			}
		}

		builder.AppendLine("    ];");
		builder.AppendLine("}");
		return builder.ToString();
	}

	private static string Format(float value)
		=> value.ToString("0.######", CultureInfo.InvariantCulture);

	private readonly record struct TerrainSampleData(float[] Heights, byte[] GroundMask);

	private readonly record struct Triangle(Vector3 A, Vector3 B, Vector3 C)
	{
		public bool TrySampleHeight(float x, float z, out float y)
		{
			var a2 = new Vector2(A.X, A.Z);
			var b2 = new Vector2(B.X, B.Z);
			var c2 = new Vector2(C.X, C.Z);
			var point = new Vector2(x, z);

			var denominator = (b2.Y - c2.Y) * (a2.X - c2.X) + (c2.X - b2.X) * (a2.Y - c2.Y);
			if (MathF.Abs(denominator) < 0.00001f)
			{
				y = 0f;
				return false;
			}

			var w1 = ((b2.Y - c2.Y) * (point.X - c2.X) + (c2.X - b2.X) * (point.Y - c2.Y)) / denominator;
			var w2 = ((c2.Y - a2.Y) * (point.X - c2.X) + (a2.X - c2.X) * (point.Y - c2.Y)) / denominator;
			var w3 = 1f - w1 - w2;

			const float epsilon = -0.0001f;
			if (w1 < epsilon || w2 < epsilon || w3 < epsilon)
			{
				y = 0f;
				return false;
			}

			y = A.Y * w1 + B.Y * w2 + C.Y * w3;
			return true;
		}

		public bool TrySampleNearestHeight(float x, float z, out float y, out float distanceSquared)
		{
			if (TrySampleHeight(x, z, out y))
			{
				distanceSquared = 0f;
				return true;
			}

			var point = new Vector2(x, z);
			var found = false;
			var bestDistanceSquared = float.MaxValue;
			var bestHeight = 0f;

			TrySampleNearestPointOnEdge(point, A, B, ref found, ref bestDistanceSquared, ref bestHeight);
			TrySampleNearestPointOnEdge(point, B, C, ref found, ref bestDistanceSquared, ref bestHeight);
			TrySampleNearestPointOnEdge(point, C, A, ref found, ref bestDistanceSquared, ref bestHeight);

			y = bestHeight;
			distanceSquared = bestDistanceSquared;
			return found;
		}

		private static void TrySampleNearestPointOnEdge(
			Vector2 point,
			Vector3 start,
			Vector3 end,
			ref bool found,
			ref float bestDistanceSquared,
			ref float bestHeight
		)
		{
			var start2 = new Vector2(start.X, start.Z);
			var end2 = new Vector2(end.X, end.Z);
			var edge = end2 - start2;
			var edgeLengthSquared = edge.LengthSquared();

			float t;
			if (edgeLengthSquared < 0.000001f)
			{
				t = 0f;
			}
			else
			{
				t = Mathf.Clamp((point - start2).Dot(edge) / edgeLengthSquared, 0f, 1f);
			}

			var closestPoint = start2 + edge * t;
			var distanceSquared = point.DistanceSquaredTo(closestPoint);
			if (found && distanceSquared >= bestDistanceSquared)
			{
				return;
			}

			found = true;
			bestDistanceSquared = distanceSquared;
			bestHeight = Mathf.Lerp(start.Y, end.Y, t);
		}
	}

	private sealed class TerrainGeometry
	{
		public Aabb Bounds { get; }
		public int MeshCount { get; }
		private readonly Triangle[] _triangles;

		private TerrainGeometry(Triangle[] triangles, Aabb bounds, int meshCount)
		{
			_triangles = triangles;
			Bounds = bounds;
			MeshCount = meshCount;
		}

		public static TerrainGeometry FromRoot(Node3D terrainRoot)
		{
			var triangleList = new System.Collections.Generic.List<Triangle>();
			var allMeshNodes = new System.Collections.Generic.List<MeshInstance3D>();
			CollectMeshNodes(terrainRoot, allMeshNodes);
			var useExplicitInclude = allMeshNodes.Exists(IsExplicitlyIncluded);
			var meshNodes = allMeshNodes.FindAll(meshNode => ShouldUseMesh(meshNode, useExplicitInclude));
			var meshCount = 0;
			var hasBounds = false;
			var min = Vector3.Zero;
			var max = Vector3.Zero;

			foreach (var meshNode in meshNodes)
			{
				var mesh = meshNode.Mesh;
				if (mesh == null)
				{
					continue;
				}

				meshCount++;
				var transform = meshNode.GlobalTransform;
				var worldAabb = transform * mesh.GetAabb();
				var worldMin = worldAabb.Position;
				var worldMax = worldAabb.End;

				if (!hasBounds)
				{
					min = worldMin;
					max = worldMax;
					hasBounds = true;
				}
				else
				{
					min = new Vector3(
						MathF.Min(min.X, worldMin.X),
						MathF.Min(min.Y, worldMin.Y),
						MathF.Min(min.Z, worldMin.Z)
					);
					max = new Vector3(
						MathF.Max(max.X, worldMax.X),
						MathF.Max(max.Y, worldMax.Y),
						MathF.Max(max.Z, worldMax.Z)
					);
				}

				for (var surface = 0; surface < mesh.GetSurfaceCount(); surface++)
				{
					var arrays = mesh.SurfaceGetArrays(surface);
					var vertices = (Vector3[])arrays[(int)Mesh.ArrayType.Vertex];
					var indices = (int[])arrays[(int)Mesh.ArrayType.Index];

					if (indices.Length > 0)
					{
						for (var i = 0; i < indices.Length; i += 3)
						{
							triangleList.Add(new Triangle(
								transform * vertices[indices[i]],
								transform * vertices[indices[i + 1]],
								transform * vertices[indices[i + 2]]
							));
						}
					}
					else
					{
						for (var i = 0; i < vertices.Length; i += 3)
						{
							triangleList.Add(new Triangle(
								transform * vertices[i],
								transform * vertices[i + 1],
								transform * vertices[i + 2]
							));
						}
					}
				}
			}

			var bounds = hasBounds
				? new Aabb(min, max - min)
				: new Aabb(Vector3.Zero, Vector3.Zero);
			return new TerrainGeometry(triangleList.ToArray(), bounds, meshCount);
		}

		private static void CollectMeshNodes(Node node, System.Collections.Generic.List<MeshInstance3D> meshNodes)
		{
			if (node is MeshInstance3D meshNode)
			{
				meshNodes.Add(meshNode);
			}

			foreach (var child in node.GetChildren())
			{
				if (child is Node childNode)
				{
					CollectMeshNodes(childNode, meshNodes);
				}
			}
		}

		private static bool ShouldUseMesh(MeshInstance3D meshNode, bool useExplicitInclude)
		{
			if (HasTaggedAncestor(meshNode, ExcludeGroupName, ExcludeMetaName))
			{
				return false;
			}

			if (!useExplicitInclude)
			{
				return true;
			}

			return HasTaggedAncestor(meshNode, IncludeGroupName, IncludeMetaName);
		}

		private static bool IsExplicitlyIncluded(MeshInstance3D meshNode)
			=> HasTaggedAncestor(meshNode, IncludeGroupName, IncludeMetaName);

		private static bool HasTaggedAncestor(Node node, string groupName, string metaName)
		{
			for (Node current = node; current != null; current = current.GetParent())
			{
				if (current.IsInGroup(groupName))
				{
					return true;
				}

				if (current.HasMeta(metaName))
				{
					var value = current.GetMeta(metaName);
					if (value.VariantType == Variant.Type.Bool && value.AsBool())
					{
						return true;
					}
				}
			}

			return false;
		}

		public float SampleHeight(float x, float z)
		{
			if (!TrySampleHeight(x, z, out var height))
			{
				throw new InvalidOperationException($"No terrain height found at ({x}, {z}).");
			}

			return height;
		}

		public bool TrySampleHeightExact(float x, float z, out float height)
			=> TrySampleHeight(x, z, out height);

		public float SampleHeightOrNearest(float x, float z, float stepX, float stepZ)
		{
			if (TrySampleHeight(x, z, out var exactHeight))
			{
				return exactHeight;
			}

			var searchStepX = MathF.Max(stepX * 0.5f, 0.001f);
			var searchStepZ = MathF.Max(stepZ * 0.5f, 0.001f);
			for (var radius = 1; radius <= 8; radius++)
			{
				for (var offsetX = -radius; offsetX <= radius; offsetX++)
				{
					for (var offsetZ = -radius; offsetZ <= radius; offsetZ++)
					{
						if (Math.Abs(offsetX) != radius && Math.Abs(offsetZ) != radius)
						{
							continue;
						}

						var sampleX = x + offsetX * searchStepX;
						var sampleZ = z + offsetZ * searchStepZ;
						if (TrySampleHeight(sampleX, sampleZ, out var nearbyHeight))
						{
							return nearbyHeight;
						}
					}
				}
			}

			if (TrySampleNearestHeight(x, z, out var nearestHeight))
			{
				return nearestHeight;
			}

			throw new InvalidOperationException($"No terrain height found near ({x}, {z}).");
		}

		private bool TrySampleNearestHeight(float x, float z, out float height)
		{
			var found = false;
			var bestDistanceSquared = float.MaxValue;
			var bestHeight = 0f;

			foreach (var triangle in _triangles)
			{
				if (!triangle.TrySampleNearestHeight(x, z, out var triangleHeight, out var distanceSquared))
				{
					continue;
				}

				if (found && distanceSquared >= bestDistanceSquared)
				{
					continue;
				}

				found = true;
				bestDistanceSquared = distanceSquared;
				bestHeight = triangleHeight;
			}

			height = bestHeight;
			return found;
		}

		private bool TrySampleHeight(float x, float z, out float height)
		{
			var found = false;
			var bestHeight = float.MinValue;

			foreach (var triangle in _triangles)
			{
				if (!triangle.TrySampleHeight(x, z, out var sampledHeight))
				{
					continue;
				}

				if (!found || sampledHeight > bestHeight)
				{
					bestHeight = sampledHeight;
					found = true;
				}
			}

			if (!found)
			{
				height = 0f;
				return false;
			}

			height = bestHeight;
			return true;
		}
	}
}
