// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetRunHandler(ReducerEventContext ctx);
        public event ResetRunHandler? OnResetRun;

        public void ResetRun()
        {
            conn.InternalCallReducer(new Reducer.ResetRun());
        }

        public bool InvokeResetRun(ReducerEventContext ctx, Reducer.ResetRun args)
        {
            if (OnResetRun == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResetRun(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetRun : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "reset_run";
        }
    }
}
