// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerInputHandler(ReducerEventContext ctx, SpacetimeDB.Types.DbVector3 direction, bool jumpRequested);
        public event UpdatePlayerInputHandler? OnUpdatePlayerInput;

        public void UpdatePlayerInput(SpacetimeDB.Types.DbVector3 direction, bool jumpRequested)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerInput(direction, jumpRequested));
        }

        public bool InvokeUpdatePlayerInput(ReducerEventContext ctx, Reducer.UpdatePlayerInput args)
        {
            if (OnUpdatePlayerInput == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerInput(
                ctx,
                args.Direction,
                args.JumpRequested
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "direction")]
            public DbVector3 Direction;
            [DataMember(Name = "jump_requested")]
            public bool JumpRequested;

            public UpdatePlayerInput(
                DbVector3 Direction,
                bool JumpRequested
            )
            {
                this.Direction = Direction;
                this.JumpRequested = JumpRequested;
            }

            public UpdatePlayerInput()
            {
                this.Direction = new();
            }

            string IReducerArgs.ReducerName => "update_player_input";
        }
    }
}
