// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Config
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "world_radius")]
        public float WorldRadius;
        [DataMember(Name = "summit_height")]
        public float SummitHeight;
        [DataMember(Name = "sandwich_speed")]
        public float SandwichSpeed;
        [DataMember(Name = "gravity")]
        public float Gravity;
        [DataMember(Name = "recovery_distance")]
        public float RecoveryDistance;
        [DataMember(Name = "summit_distance")]
        public float SummitDistance;
        [DataMember(Name = "topping_drop_tilt")]
        public float ToppingDropTilt;
        [DataMember(Name = "topping_drop_impact_speed")]
        public float ToppingDropImpactSpeed;
        [DataMember(Name = "jump_impulse")]
        public float JumpImpulse;

        public Config(
            int Id,
            float WorldRadius,
            float SummitHeight,
            float SandwichSpeed,
            float Gravity,
            float RecoveryDistance,
            float SummitDistance,
            float ToppingDropTilt,
            float ToppingDropImpactSpeed,
            float JumpImpulse
        )
        {
            this.Id = Id;
            this.WorldRadius = WorldRadius;
            this.SummitHeight = SummitHeight;
            this.SandwichSpeed = SandwichSpeed;
            this.Gravity = Gravity;
            this.RecoveryDistance = RecoveryDistance;
            this.SummitDistance = SummitDistance;
            this.ToppingDropTilt = ToppingDropTilt;
            this.ToppingDropImpactSpeed = ToppingDropImpactSpeed;
            this.JumpImpulse = JumpImpulse;
        }

        public Config()
        {
        }
    }
}
