// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameEvent
    {
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "event_type")]
        public string EventType;
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "topping_id")]
        public int ToppingId;
        [DataMember(Name = "message")]
        public string Message;

        public GameEvent(
            SpacetimeDB.Timestamp CreatedAt,
            string EventType,
            int PlayerId,
            int ToppingId,
            string Message
        )
        {
            this.CreatedAt = CreatedAt;
            this.EventType = EventType;
            this.PlayerId = PlayerId;
            this.ToppingId = ToppingId;
            this.Message = Message;
        }

        public GameEvent()
        {
            this.EventType = "";
            this.Message = "";
        }
    }
}
