// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerMotion
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "vertical_velocity")]
        public float VerticalVelocity;

        public PlayerMotion(
            SpacetimeDB.Identity Identity,
            float VerticalVelocity
        )
        {
            this.Identity = Identity;
            this.VerticalVelocity = VerticalVelocity;
        }

        public PlayerMotion()
        {
        }
    }
}
