// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RunState
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "shuffle_seed")]
        public uint ShuffleSeed;

        public RunState(
            int Id,
            uint ShuffleSeed
        )
        {
            this.Id = Id;
            this.ShuffleSeed = ShuffleSeed;
        }

        public RunState()
        {
        }
    }
}
