// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SandwichMotion
    {
        [DataMember(Name = "sandwich_id")]
        public int SandwichId;
        [DataMember(Name = "pitch_velocity")]
        public float PitchVelocity;
        [DataMember(Name = "roll_velocity")]
        public float RollVelocity;

        public SandwichMotion(
            int SandwichId,
            float PitchVelocity,
            float RollVelocity
        )
        {
            this.SandwichId = SandwichId;
            this.PitchVelocity = PitchVelocity;
            this.RollVelocity = RollVelocity;
        }

        public SandwichMotion()
        {
        }
    }
}
