// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Sandwich
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "tilt")]
        public float Tilt;
        [DataMember(Name = "pitch")]
        public float Pitch;
        [DataMember(Name = "roll")]
        public float Roll;
        [DataMember(Name = "yaw")]
        public float Yaw;
        [DataMember(Name = "attached_player_count")]
        public int AttachedPlayerCount;
        [DataMember(Name = "at_summit")]
        public bool AtSummit;
        [DataMember(Name = "completed")]
        public bool Completed;
        [DataMember(Name = "tick")]
        public ulong Tick;

        public Sandwich(
            int Id,
            DbVector3 Position,
            DbVector3 Velocity,
            float Tilt,
            float Pitch,
            float Roll,
            float Yaw,
            int AttachedPlayerCount,
            bool AtSummit,
            bool Completed,
            ulong Tick
        )
        {
            this.Id = Id;
            this.Position = Position;
            this.Velocity = Velocity;
            this.Tilt = Tilt;
            this.Pitch = Pitch;
            this.Roll = Roll;
            this.Yaw = Yaw;
            this.AttachedPlayerCount = AttachedPlayerCount;
            this.AtSummit = AtSummit;
            this.Completed = Completed;
            this.Tick = Tick;
        }

        public Sandwich()
        {
            this.Position = new();
            this.Velocity = new();
        }
    }
}
