// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Topping
    {
        [DataMember(Name = "topping_id")]
        public int ToppingId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "layer_order")]
        public int LayerOrder;
        [DataMember(Name = "state")]
        public ToppingState State;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "attached_offset")]
        public DbVector3 AttachedOffset;
        [DataMember(Name = "drop_count")]
        public int DropCount;

        public Topping(
            int ToppingId,
            string Name,
            int LayerOrder,
            ToppingState State,
            DbVector3 Position,
            DbVector3 Velocity,
            DbVector3 AttachedOffset,
            int DropCount
        )
        {
            this.ToppingId = ToppingId;
            this.Name = Name;
            this.LayerOrder = LayerOrder;
            this.State = State;
            this.Position = Position;
            this.Velocity = Velocity;
            this.AttachedOffset = AttachedOffset;
            this.DropCount = DropCount;
        }

        public Topping()
        {
            this.Name = "";
            this.Position = new();
            this.Velocity = new();
            this.AttachedOffset = new();
        }
    }
}
