// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConfigHandle : RemoteTableHandle<EventContext, Config>
        {
            protected override string RemoteTableName => "config";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Config row) => row.Id;

                public IdUniqueIndex(ConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Config row) => row.Id;
        }

        public readonly ConfigHandle Config;
    }

    public sealed class ConfigCols
    {
        public global::SpacetimeDB.Col<Config, int> Id { get; }
        public global::SpacetimeDB.Col<Config, float> WorldRadius { get; }
        public global::SpacetimeDB.Col<Config, float> SummitHeight { get; }
        public global::SpacetimeDB.Col<Config, float> SandwichSpeed { get; }
        public global::SpacetimeDB.Col<Config, float> Gravity { get; }
        public global::SpacetimeDB.Col<Config, float> RecoveryDistance { get; }
        public global::SpacetimeDB.Col<Config, float> SummitDistance { get; }
        public global::SpacetimeDB.Col<Config, float> ToppingDropTilt { get; }
        public global::SpacetimeDB.Col<Config, float> ToppingDropImpactSpeed { get; }

        public ConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Config, int>(tableName, "id");
            WorldRadius = new global::SpacetimeDB.Col<Config, float>(tableName, "world_radius");
            SummitHeight = new global::SpacetimeDB.Col<Config, float>(tableName, "summit_height");
            SandwichSpeed = new global::SpacetimeDB.Col<Config, float>(tableName, "sandwich_speed");
            Gravity = new global::SpacetimeDB.Col<Config, float>(tableName, "gravity");
            RecoveryDistance = new global::SpacetimeDB.Col<Config, float>(tableName, "recovery_distance");
            SummitDistance = new global::SpacetimeDB.Col<Config, float>(tableName, "summit_distance");
            ToppingDropTilt = new global::SpacetimeDB.Col<Config, float>(tableName, "topping_drop_tilt");
            ToppingDropImpactSpeed = new global::SpacetimeDB.Col<Config, float>(tableName, "topping_drop_impact_speed");
        }
    }

    public sealed class ConfigIxCols
    {
        public global::SpacetimeDB.IxCol<Config, int> Id { get; }

        public ConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Config, int>(tableName, "id");
        }
    }
}
