// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameEventHandle : RemoteEventTableHandle<EventContext, GameEvent>
        {
            protected override string RemoteTableName => "game_event";

            internal GameEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly GameEventHandle GameEvent;
    }

    public sealed class GameEventCols
    {
        public global::SpacetimeDB.Col<GameEvent, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<GameEvent, string> EventType { get; }
        public global::SpacetimeDB.Col<GameEvent, int> PlayerId { get; }
        public global::SpacetimeDB.Col<GameEvent, int> ToppingId { get; }
        public global::SpacetimeDB.Col<GameEvent, string> Message { get; }

        public GameEventCols(string tableName)
        {
            CreatedAt = new global::SpacetimeDB.Col<GameEvent, SpacetimeDB.Timestamp>(tableName, "created_at");
            EventType = new global::SpacetimeDB.Col<GameEvent, string>(tableName, "event_type");
            PlayerId = new global::SpacetimeDB.Col<GameEvent, int>(tableName, "player_id");
            ToppingId = new global::SpacetimeDB.Col<GameEvent, int>(tableName, "topping_id");
            Message = new global::SpacetimeDB.Col<GameEvent, string>(tableName, "message");
        }
    }

    public sealed class GameEventIxCols
    {

        public GameEventIxCols(string tableName)
        {
        }
    }
}
