// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SandwichHandle : RemoteTableHandle<EventContext, Sandwich>
        {
            protected override string RemoteTableName => "sandwich";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Sandwich row) => row.Id;

                public IdUniqueIndex(SandwichHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SandwichHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Sandwich row) => row.Id;
        }

        public readonly SandwichHandle Sandwich;
    }

    public sealed class SandwichCols
    {
        public global::SpacetimeDB.Col<Sandwich, int> Id { get; }
        public global::SpacetimeDB.Col<Sandwich, DbVector3> Position { get; }
        public global::SpacetimeDB.Col<Sandwich, DbVector3> Velocity { get; }
        public global::SpacetimeDB.Col<Sandwich, float> Tilt { get; }
        public global::SpacetimeDB.Col<Sandwich, int> AttachedPlayerCount { get; }
        public global::SpacetimeDB.Col<Sandwich, bool> AtSummit { get; }
        public global::SpacetimeDB.Col<Sandwich, bool> Completed { get; }
        public global::SpacetimeDB.Col<Sandwich, ulong> Tick { get; }

        public SandwichCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Sandwich, int>(tableName, "id");
            Position = new global::SpacetimeDB.Col<Sandwich, DbVector3>(tableName, "position");
            Velocity = new global::SpacetimeDB.Col<Sandwich, DbVector3>(tableName, "velocity");
            Tilt = new global::SpacetimeDB.Col<Sandwich, float>(tableName, "tilt");
            AttachedPlayerCount = new global::SpacetimeDB.Col<Sandwich, int>(tableName, "attached_player_count");
            AtSummit = new global::SpacetimeDB.Col<Sandwich, bool>(tableName, "at_summit");
            Completed = new global::SpacetimeDB.Col<Sandwich, bool>(tableName, "completed");
            Tick = new global::SpacetimeDB.Col<Sandwich, ulong>(tableName, "tick");
        }
    }

    public sealed class SandwichIxCols
    {
        public global::SpacetimeDB.IxCol<Sandwich, int> Id { get; }

        public SandwichIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Sandwich, int>(tableName, "id");
        }
    }
}
