// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ToppingHandle : RemoteTableHandle<EventContext, Topping>
        {
            protected override string RemoteTableName => "topping";

            public sealed class ToppingIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Topping row) => row.ToppingId;

                public ToppingIdUniqueIndex(ToppingHandle table) : base(table) { }
            }

            public readonly ToppingIdUniqueIndex ToppingId;

            internal ToppingHandle(DbConnection conn) : base(conn)
            {
                ToppingId = new(this);
            }

            protected override object GetPrimaryKey(Topping row) => row.ToppingId;
        }

        public readonly ToppingHandle Topping;
    }

    public sealed class ToppingCols
    {
        public global::SpacetimeDB.Col<Topping, int> ToppingId { get; }
        public global::SpacetimeDB.Col<Topping, string> Name { get; }
        public global::SpacetimeDB.Col<Topping, int> LayerOrder { get; }
        public global::SpacetimeDB.Col<Topping, ToppingState> State { get; }
        public global::SpacetimeDB.Col<Topping, DbVector3> Position { get; }
        public global::SpacetimeDB.Col<Topping, DbVector3> Velocity { get; }
        public global::SpacetimeDB.Col<Topping, DbVector3> AttachedOffset { get; }
        public global::SpacetimeDB.Col<Topping, int> DropCount { get; }

        public ToppingCols(string tableName)
        {
            ToppingId = new global::SpacetimeDB.Col<Topping, int>(tableName, "topping_id");
            Name = new global::SpacetimeDB.Col<Topping, string>(tableName, "name");
            LayerOrder = new global::SpacetimeDB.Col<Topping, int>(tableName, "layer_order");
            State = new global::SpacetimeDB.Col<Topping, ToppingState>(tableName, "state");
            Position = new global::SpacetimeDB.Col<Topping, DbVector3>(tableName, "position");
            Velocity = new global::SpacetimeDB.Col<Topping, DbVector3>(tableName, "velocity");
            AttachedOffset = new global::SpacetimeDB.Col<Topping, DbVector3>(tableName, "attached_offset");
            DropCount = new global::SpacetimeDB.Col<Topping, int>(tableName, "drop_count");
        }
    }

    public sealed class ToppingIxCols
    {
        public global::SpacetimeDB.IxCol<Topping, int> ToppingId { get; }

        public ToppingIxCols(string tableName)
        {
            ToppingId = new global::SpacetimeDB.IxCol<Topping, int>(tableName, "topping_id");
        }
    }
}
