// Auto-generated by ToppingProfileExporter.cs
public static partial class ToppingShapeData
{
    public static ToppingShapeProfile GetProfile(string name)
        => name switch
        {
            "Lettuce" => new ToppingShapeProfile("Lettuce", 4.834908f, 3.151507f, -0.533646f, 0.533646f, 162.6259f, 0.15f, 2.5f),
            "Bacon" => new ToppingShapeProfile("Bacon", 2.650475f, 2.166309f, -0.627048f, 0.627048f, 72.00696f, 0.15f, 2.5f),
            "Cheese" => new ToppingShapeProfile("Cheese", 2.831337f, 2.103153f, -0.1024f, 0.1024f, 12.1953f, 0.15f, 2.5f),
            "Tomato" => new ToppingShapeProfile("Tomato", 0.900002f, 0.9f, -0.15f, 0.15f, 2.430003f, 0.15f, 2.5f),
            "TopBread" => new ToppingShapeProfile("TopBread", 4.150002f, 1.25f, -0.625f, 0.625f, 64.84377f, 0.15f, 2.5f),
            "BottomBread" => new ToppingShapeProfile("BottomBread", 4.150002f, 1.25f, -0.625f, 0.625f, 64.8438f, 0.15f, 2.5f),
            _ => Default,
        };
}
